// Builds docs/benchmarks/PHASE4A.md from the per-browser JSON files that `npm run bench` writes.
// Usage: node scripts/bench-report.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const dir = resolve(process.cwd(), 'docs/benchmarks');
const files = readdirSync(dir).filter((f) => /^phase4a-.*\.json$/.test(f)).sort();
const runs = files.map((f) => ({ f, ...JSON.parse(readFileSync(resolve(dir, f), 'utf8')) }));
const tiers = ['50k', '200k', '500k', '1M', '2.56M'];
const sec = (ms) => (ms === undefined ? '—' : (ms / 1000).toFixed(1));
const cell = (r, fn) => (r ? (r.ok ? fn(r) : `FAILED: ${r.error ?? 'unknown'}`) : 'not run');

let md = '# Phase 4a benchmarks\n\nGenerated by `scripts/bench-report.mjs` from `docs/benchmarks/phase4a-*.json` (`npm run bench`).\n\n';
md += 'Each tier runs the shell\'s orogen pipeline (stages 1-5 and 8) in the engine worker through the real app path, one fresh page per tier, seed 12345, debug layers off.\n\n';
md += '- **generation** is the sum of the six stage durations measured from progress events; **total** also includes transferring the mesh, building the globe and painting the first layer.\n';
md += '- **working set** is the logical size of mesh and layer arrays in the worker (every browser).\n';
md += '- **peak RSS** is the peak resident memory of all processes started from the Playwright browser install, sampled with `ps` every 100 ms (macOS and Linux). It covers page, worker and helpers, and includes the browser\'s own baseline (shown as the second figure).\n\n';
for (const r of runs) {
  const m = r.meta;
  md += `## ${m.browser} on ${m.platform}\n\n${m.cpu}, ${m.cores} cores, ${m.ramGB} GB RAM, ${m.date.slice(0, 10)}\n\n`;
  md += '| Tier | Cells | Generation (s) | Total (s) | Working set (MB) | Peak RSS (MB) / baseline | Slowest stage |\n|---|---|---|---|---|---|---|\n';
  for (const t of tiers) {
    const x = r.results.find((q) => q.tier === t);
    const slow = x?.ok ? Object.entries(x.stagesMs).sort((a, b) => b[1] - a[1])[0] : undefined;
    md += `| ${t} | ${x ? x.cells.toLocaleString('en') : '—'} | ${cell(x, (q) => sec(q.generationMs))} | ${cell(x, (q) => sec(q.totalMs))} | ${cell(x, (q) => q.workingSetMB)} | ${x ? (x.peakRssMB === null ? 'n/a' : `${x.peakRssMB} / ${x.baselineRssMB}`) : '—'} | ${slow ? `${slow[0]} ${sec(slow[1])} s` : '—'} |\n`;
  }
  md += '\n';
}
md += '## Against the §6.2 budget\n\n| Tier | Budget | Measured peak RSS, worst browser |\n|---|---|---|\n';
const budget = { '50k': '< 100 MB (preview)', '200k': '< 100 MB (preview)', '500k': '150-300 MB (standard)', '1M': '150-300 MB (standard)', '2.56M': '~400-600 MB (max)' };
for (const t of tiers) {
  const peaks = runs.map((r) => r.results.find((q) => q.tier === t)).filter((x) => x?.ok && x.peakRssMB != null).map((x) => x.peakRssMB);
  md += `| ${t} | ${budget[t]} | ${peaks.length ? Math.max(...peaks) + ' MB' : 'n/a'} |\n`;
}
writeFileSync(resolve(dir, 'PHASE4A.md'), md);
console.log(`wrote ${resolve(dir, 'PHASE4A.md')}`);
