// Packs the driver's text output into vectors.json: { sources, fns: { name: ["in out", "in1 in2 out", ...] } }.
// Original MapMaker tooling.
import { readFileSync } from 'node:fs';
import process from 'node:process';
const [, , vecPath, shaPath] = process.argv;
const fns = {};
for (const line of readFileSync(vecPath, 'utf8').split('\n')) {
  if (!line) continue;
  const [name, ...rest] = line.split(' ');
  (fns[name] ??= []).push(rest.join(' '));
}
const sources = Object.fromEntries(readFileSync(shaPath, 'utf8').split('\n').filter(Boolean).map((l) => { const [h, f] = l.split(/\s+/); return [f, h]; }));
const out = {
  note: 'Generated by tools/fdlibm-vectors/gen.sh from unmodified netlib fdlibm 5.3 (log2: FreeBSD msun). Each entry is hex IEEE-754 bit patterns: "x result" or "x y result". Do not edit.',
  sources,
  fns: Object.fromEntries(Object.keys(fns).sort().map((k) => [k, fns[k]])),
};
process.stdout.write(JSON.stringify(out) + '\n');
