#define sin fd_sin
#define cos fd_cos
#define tan fd_tan
#define asin fd_asin
#define acos fd_acos
#define atan fd_atan
#define atan2 fd_atan2
#define sinh fd_sinh
#define cosh fd_cosh
#define tanh fd_tanh
#define asinh fd_asinh
#define acosh fd_acosh
#define atanh fd_atanh
#define exp fd_exp
#define expm1 fd_expm1
#define log fd_log
#define log1p fd_log1p
#define log10 fd_log10
#define pow fd_pow
#define cbrt fd_cbrt
#define fabs fd_fabs
#define floor fd_floor
#define ceil fd_ceil
#define scalbn fd_scalbn
#define copysign fd_copysign
#define finite fd_finite
#define isnan fd_isnan
#define rint fd_rint
#define fmod fd_fmod
#define ldexp fd_ldexp
#define frexp fd_frexp
#define modf fd_modf
#define logb fd_logb
#define ilogb fd_ilogb
#define nextafter fd_nextafter
#define erf fd_erf
#define erfc fd_erfc
